server:
  port: 8080
spring:
  application:
    name: Resource-Tracker
  h2:
    console:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
  data:
    mongodb:
      database: ApplicationTest
      grid-fs-database: fieldstore
      host: localhost
      port: 27017

#spring.mvc.view.prefix = /views/
#spring.mvc.view.suffix = .html

#Local MongoDB config
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root

# App config
#server.servlet.context-path=/user
      